### ISSUE TITLE
Slow

### ISSUE THREAD

**Issue by icatSolutions** [nicklockwood/Euclid#12]
Why are these operations soooo slow? 
Getting the polygons from SCNNode into Mesh() takes ages.
The JS counterpart application is extremely fast. 
Is this a bug?

**Comment by nicklockwood** [comment]
@icatSolutions could be. Have you tried running Euclid in release mode rather than debug, as Swift performance is quite sensitive to optimizations.

If it's still slow in release mode, can you supply some sample code demonstrating an operation that's slow in Euclid and fast in JS? Then I can try to identify the bottleneck.

**Comment by icatSolutions** [comment]
Thanks for the swift reply. 

Branch: develop
Scheme: release

```
let cube = Mesh.cube(size: 0.8, material: UIColor.red)
let sphere = Mesh.sphere(slices: 200, material: UIColor.blue)
```

The above crashes the app (if you reduce the slices to 140 -> I think it takes a good 12 to 15sec to do the "subtraction"

**The same parameters where you based the Swift project on (JS) runs in 0.5 sec... (stacks)**
(http://github.com/evanw/csg.js/)

Also the following code has the some issues:

```
        let capsuleGeometry = SCNCapsule(capRadius: 0.5, height: 2)
        let torusGeometry = SCNTorus(ringRadius: 0.35, pipeRadius: 0.15)
        capsuleGeometry.capSegmentCount = 80
        torusGeometry.pipeSegmentCount = 200       
        var torus = Mesh(scnGeometry: torusGeometry)?.translated(by: Vector(0.5, 0, 0))
        let capsule = Mesh(scnGeometry: capsuleGeometry)
        let mesh = capsule!.subtract(torus!)
```


1. The segmentCount for both objects is not taken into account

Can you please advise? 
cheers

**Comment by icatSolutions** [comment]
@nicklockwood hello. Did you ever find a solution for the above? 
Thank you

**Comment by nicklockwood** [comment]
@icatSolutions not yet - I've been focussed on other tasks, but I should get to this soon.

**Comment by nicklockwood** [comment]
@icatSolutions I'm not really sure why this is, but it seems that changes to the segmentCount on SCNGeometry doesn't affect the output from sources (maybe some kind of internal caching bug?).

A workaround is to copy the geometry after changing it, like this:

```swift
var capsule = SCNCapsule(capRadius: 0.5, height: 2)
capsule.capSegmentCount = 80
capsule = capsule.copy() as! SCNCapsule
```

**Comment by icatSolutions** [comment]
@nicklockwood Thank you. Will try..

Any thoughts about this:

```
let cube = Mesh.cube(size: 0.8, material: UIColor.red)
let sphere = Mesh.sphere(slices: 200, material: UIColor.blue)
The above crashes the app (if you reduce the slices to 140 -> I think it takes a good 12 to 15sec to do the "subtraction"
```

The same parameters where you based the Swift project on (JS) runs in 0.5 sec... (stacks)
(http://github.com/evanw/csg.js/)

**Comment by nicklockwood** [comment]
I'm not exactly sure what the cause of the performance issues is. I profiled it and it's spending a lot of time in array allocations, which I can probably reduce but it will require significant refactoring.

It also doesn't really explain why it's slower than JS, which presumably has to do a similar amount of allocation.

Another possibility it's due to the extra stuff that my implementation does that the original JS version doesn't, such as stitching adjacent polygons back together after CSG to prevent hundreds of tiny coplanar triangles.

**Comment by nicklockwood** [comment]
As for the crash, that's caused by a stack overflow due to recursion. The workaround I'd suggest is to create a new Thread with a larger stack size and run the operation inside it.

**Comment by icatSolutions** [comment]
I understand. We are grateful to your work and commitment to open source it. We find great value to your project and we would like to donate an amount towards refactoring the process (or finding a solution) in order to “speed things up” if that would help. Please get in touch should you wish to discuss further. Thank you. 
info@icatmed.com

**Comment by nicklockwood** [comment]
@icatSolutions thank you for the offer, but that won't be necessary :-)

I have some good news - I was able to find a simple 2X speedup by removing an array allocation. I've pushed the changes to the develop branch.

I know it's not the order-of-magnitude improvement you're looking for, but I'll keep digging and hopefully there will be some other low-hanging fruit.

**Comment by nicklockwood** [comment]
@icatSolutions I managed to get another 2X speedup in the CSG logic in version 0.2.3. Also, thanks to a fix from @andygeers the conversion to SceneKit mesh is also now much quicker.

**Comment by icatSolutions** [comment]
@nicklockwood @andygeers Thank you both for your excellent work (both). You are very talented engineers.

**Comment by nicklockwood** [comment]
@icatSolutions I got another big speed boost by not splitting polygons when building the BSP. I'm not 100% sure there aren't any negative consequences to this (it seems to increase the resultant poly count in some cases), but so far it looks promising. I've pushed a new version to develop if you want to check it out.

**Comment by andygeers** [comment]
@nicklockwood I have a feeling the changes have some negative consequences....

![Simulator Screen Shot - iPhone 11 Pro Max - 2020-01-20 at 20 54 01](https://user-images.githubusercontent.com/1673899/72757497-07e27100-3bc8-11ea-9e15-4637ecb16489.png)

...although I also had to change my method since I had been sneakily using `mesh.polygons += otherMesh.polygons` instead of union (it seemed to be quicker and actually produced between results) whereas in develop `polygons` is a constant so I had to go back to union - but trying to compare that behaviour with the master branch is crashing because the assert inside `union` is failing that apparently not all of the polygons are convex - it's a Mesh initialised from scnGeometry loaded from a USDZ file.

**Comment by nicklockwood** [comment]
@andygeers I've fixed a few bugs - try pulling again.

**Comment by nicklockwood** [comment]
@andygeers merging meshes by appending polygons was never particularly reliable because it  can produces a self-intersecting shape, which may then not work correctly for CSG, however if you want to do that you still can - just get the (ready-only) polygon arrays from the two meshes and concatenate them, then create a new Mesh.

**Comment by andygeers** [comment]
@nicklockwood Did you push those bug fixes? I've tried using your suggested methods of just concatenating the two lists of polygons, and I still get all of the glitches. But I can't see any new commits to your develop branch since the first time I tried. I've been trying to put together a simple test case to reproduce the issue but haven't quite managed yet. Will keep trying for you!

**Comment by nicklockwood** [comment]
@andygeers I rebased the fixes into the relevant commits, but you should find that the asserts are no longer there.

There does seem to be a bug with unions that I'm currently trying to track down. I'm not aware of any other issues right now, but a test case for any issues you're seeing would certainly be helpful.

**Comment by andygeers** [comment]
@nicklockwood In my branch https://github.com/andygeers/Euclid/tree/mesh-test I *think* I've reproduced some kind of issue. If you rotate the mesh round and look at the red bits clipped by the plane, you'll see a few holes that shouldn't be there. If you were to then uncomment the `.subtract(hole)` bit those holes would then cause bad things to happen. If I run this same test using the `master` branch I don't get those holes (though curiously I do get a few extra random polygons appearing - but somehow that worries me less)

**Comment by nicklockwood** [comment]
@andygeers thanks, I believe I've now fixed the holes bug (at a slight cost to the performance).

**Comment by nicklockwood** [comment]
The latest update is *dramatically* faster for convex meshes (sphere's, cubes, etc). Unfortunately there's not much improvement for concave meshes, and also I need a fast way to detect convexness because currently it only works for meshes created using Euclid shape primitives.

**Comment by andygeers** [comment]
@nicklockwood It's looking loads better in my main app... Although I still get these weird "stilts" (with matching holes inside the house): 

![Simulator Screen Shot - iPhone 11 Pro Max - 2020-01-21 at 22 45 56](https://user-images.githubusercontent.com/1673899/72850001-f66c9800-3c9f-11ea-95d7-259ffb18b8f6.png)

- But so far no joy in reproducing this in the test app, so it could still be something I'm doing wrong somewhere... Though I honestly don't know what's different between the code I've put in the test app and my actual app right now...

I tried switching my main app over to proper unions (rather than just concatenating polygons) and it produces identical results.

**Comment by nicklockwood** [comment]
@andygeers I found and fixed another bug that might relate to your "stilts" glitch. Try pulling develop again.

**Comment by andygeers** [comment]
@nicklockwood Still happens I'm afraid. I updated my https://github.com/andygeers/Euclid/tree/mesh-test branch to demonstrate the problem (sorry it's so slow!) - it contains a lot more of my actual app code in it than I would have liked, but at least you can see the issue. It doesn't incorporate your latest changes yet (got a conflict when doing rebase and have to head off now) but I did try your latest changes in my main app with no change.

**Comment by nicklockwood** [comment]
@andygeers thanks - I've pulled your project if you'd like to take it down.

**Comment by nicklockwood** [comment]
@andygeers this is now fixed on develop.

**Comment by nicklockwood** [comment]
@andygeers I had to add some hacks to support your project specifically, which may well not work for other similar geometries. I believe that the reason for the weird "stilts" and other glitches you are seeing is that the 01_bricks.usdz mesh you are using has holes in it, which breaks the CSG logic.

In future I will hopefully find ways to compensate for this by auto-sealing holes in the mesh (or something), but in the meantime I expect that you'll keep seeing similar glitches unless you use fully solid geometry.

**Comment by andygeers** [comment]
@nicklockwood I will check again - but the method I am using to generate is intended to guarantee that it doesn't have holes in it (it takes a PNG image and generates a flat surface on top then seals in the sides, top and bottom, and the back). 
I've tried to test on my main app but I can't get as far as it rendering because it keeps failing the assertions inside Mesh.init(unchecked: ) saying that not all of the polygons satisfy the `isConvex` bit. Is it working in my test branch?
Thank you so much for all your work on this - I so appreciate it. Since we're both in London I'll have to buy you a beer some time!

**Comment by nicklockwood** [comment]
@andygeers 

> I will check again - but the method I am using to generate is intended to guarantee that it doesn't have holes in it.

I think there may be a bug in your sealing logic. Looking at the USD file (just in Xcode, not through Euclid), the edge polygons here don't seem to line up with the bricks.

<img width="660" alt="Screenshot 2020-01-23 at 08 45 29" src="https://user-images.githubusercontent.com/546885/72969199-ea2a2d00-3dbc-11ea-87e7-e80ea7dcac41.png">

I also tried converting the file to OBJ format and then opening it in Cheetah 3D, which reported that the model is not watertight (and also rendered it with weird glitches at the edges, suggesting there's some problem with the geometry there).

<img width="619" alt="Screenshot 2020-01-23 at 08 49 06" src="https://user-images.githubusercontent.com/546885/72969424-586eef80-3dbd-11ea-84e8-103a3f4f6e6a.png">

**Comment by nicklockwood** [comment]
@andygeers 

> I've tried to test on my main app but I can't get as far as it rendering because it keeps failing the assertions inside Mesh.init(unchecked: ) saying that not all of the polygons satisfy the isConvex bit. Is it working in my test branch?

Sorry about that - I only tested it in release mode. There is indeed a slight bug there, but I've fixed that now and it makes no difference to the rendering problem.

**Comment by nicklockwood** [comment]
@andygeers the assertion failures should now be fixed on develop.

**Comment by andygeers** [comment]
@nicklockwood 

> I think there may be a bug in your sealing logic. Looking at the USD file (just in Xcode, not through Euclid), the edge polygons here don't seem to line up with the bricks.

Ah, good spot. I used to have a bug like that which i fixed - maybe I never regenerated this particular mesh. Or maybe there's a second similar bug! Sorry for any time wasted.

**Comment by andygeers** [comment]
@nicklockwood Working beautifully now - THANK YOU! I suspect that somehow my old buggy USDZ file made it into that test branch, as I didn't actually need to change anything to get my main app working now running against the official Euclid 0.3.0

**Comment by nicklockwood** [comment]
@andygeers I shipped the hack to support your broken file in 3.0, so it's possible you're still using it in your main app too. If you can send me the fixed USDZ I can verify if it's safe to remove the hack in the next release.

**Comment by nicklockwood** [comment]
@icatSolutions I'm going to close this issue. Performance tuning is never really "completed", as there is always room for improvement, but CSG operations are now between 10x and 100x faster (depending on whether the input meshes are convex).

If you encounter any other cases where it seems slower than you'd expect, feel free to open a new issue.

**Comment by PrashantKT** [comment]
@nicklockwood  I am facing the same issue - operation is slow in Debug mode - but in release mode it is okay  

Is there any workaround for that ? 

can we do mesh decimation  to reduce the STL or OBJ File size by may be decreasing Polygons 

I think this library is more capable then any other to do this 😊

**Comment by nicklockwood** [comment]
@PrashantKT the slowness in debug mode is mainly due to the Swift optimizer. The best option is to set the Euclid module's optimization level to -Os in the build settings for debug mode.

Euclid doesn't currently have a mechanism for mesh decimation/simplification, but it's maybe something I could add if I can find a good algorithm.

**Comment by PrashantKT** [comment]
@nicklockwood I have integrated  files manually - because I need to modify some file - Do I need to create framework now to change the optimisation level ? could you please guide it how to do this

**Comment by nicklockwood** [comment]
If you have added the files manually without a sub-project, it's not possible to chnage the optimization level unless you do it for your whole project. The best option is to integrate by dragging the entire Euclid Xcode project into yours as a sub-project, then you can still edit the files, but also change the optimization level separately.

If you have done that, all you need to do is change this setting for the Euclid target:
<img width="582" alt="Screenshot 2022-01-24 at 12 53 52" src="https://user-images.githubusercontent.com/546885/150786440-92ca415a-c60a-4e82-9754-7305e851ae52.png">

**Comment by nicklockwood** [comment]
Note that this will make it harder to debug any changes you make to Euclid files. If you need to debug Euclid, switch back to No optimization for debug mode, then switch back again when you are finished testing.

**Comment by PrashantKT** [comment]
@nicklockwood  Thank you !! I did the same - But I am not able to access some of the classes  , 

I have checked Polygon is already Public but still not able to access it 

<img width="772" alt="Screenshot 2022-01-24 at 6 26 37 PM" src="https://user-images.githubusercontent.com/35359315/150786904-c6a10cee-a17b-40af-a2cb-20b42140e0d5.png">

**Comment by PrashantKT** [comment]
@nicklockwood  Thank you it is working !! - Sir Are you able to find solution for decimation (reduce the SIZE / POLYGON) of object ?
